# encoding utf-8
# Copyright (c) Universidade Federal Fluminense (UFF).
# This file is part of SAPOS. Please, consult the license terms in the LICENSE file.
###Arquivo com Propriedades gerais utilizada no sistema

#
##Scholarship
#
scholarship_year_range: 20